before_script:
    - apt-get update -y
    - apt-get install -y npm
    - ./tests/install.sh
    - nvm install node
    - nvm use node
    - npm install && npm install -g mocha

test:
    script:
        - cd tests/ && make